In [3]:
import torch as t
t.Tensor(3, 4)
print(t.__version__)

2.3.1


In [7]:
# 生成一个随机Tensor
x = t.rand(2, 3, 4)
x

tensor([[[0.6997, 0.9583, 0.6578, 0.5524],
         [0.4812, 0.3876, 0.1556, 0.6982],
         [0.8647, 0.7170, 0.7825, 0.5398]],

        [[0.2774, 0.9643, 0.8283, 0.1454],
         [0.2469, 0.8175, 0.5463, 0.8045],
         [0.5787, 0.7236, 0.2545, 0.8267]]])

In [9]:
# 查看x的形状
print(x.size())

print(x.size()[0], x.size()[1], x.size()[2])

torch.Size([2, 3, 4])
2 3 4


In [11]:
#两个Tensor相加
y = t.rand(2, 3, 4)
z = x + y
z

tensor([[[1.6274, 1.8459, 0.9935, 0.6858],
         [0.8871, 0.5137, 0.2799, 0.8184],
         [1.7442, 0.7983, 1.5431, 0.9799]],

        [[0.8066, 1.0363, 1.7529, 0.5800],
         [0.4507, 1.3566, 1.2787, 1.1608],
         [0.8231, 1.5110, 0.6946, 1.7349]]])

In [13]:
# 注意两个张量对应的维度要匹配
y1 = t.rand(3, 4, 2)
z1 = x + y1
z1

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [15]:
#通过函数add实现加法
print(t.add(x, y))

tensor([[[1.6274, 1.8459, 0.9935, 0.6858],
         [0.8871, 0.5137, 0.2799, 0.8184],
         [1.7442, 0.7983, 1.5431, 0.9799]],

        [[0.8066, 1.0363, 1.7529, 0.5800],
         [0.4507, 1.3566, 1.2787, 1.1608],
         [0.8231, 1.5110, 0.6946, 1.7349]]])


In [17]:
x = t.rand(1,3,4)
y = t.rand(2,3,1)
z = x + y
print(x.size())
print(y.size())
print(z.size())

torch.Size([1, 3, 4])
torch.Size([2, 3, 1])
torch.Size([2, 3, 4])


In [19]:
x = t.rand(2,3,4)
y = t.rand(1,3,2)
z = x + y
print(x.size())
print(y.size())
print(z.size())

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

In [21]:
#另外一个写法，结果输出到提前定义好的Tensor中
result = t.Tensor(2, 3, 4)
x = t.rand(2, 3, 4)
y = t.rand(2, 3, 4)
t.add(x, y, out = result)
result

tensor([[[1.1474, 1.1974, 0.5056, 1.5297],
         [1.2836, 1.6238, 1.2727, 1.0355],
         [0.6783, 0.7793, 0.4457, 0.4739]],

        [[0.8815, 0.1135, 0.4407, 0.3064],
         [0.5930, 1.0446, 0.6721, 0.9688],
         [0.8807, 1.4219, 0.2596, 1.3455]]])

In [23]:
# 函数名带下划线 x.add_(y)会改变x，不带下划线x.add(y) 返回一个新的Tensor，x不改变
print(x)
x.add(y)
print(x)
x.add_(y)
print(x)

tensor([[[0.9059, 0.3362, 0.4069, 0.6205],
         [0.8584, 0.9003, 0.9585, 0.0581],
         [0.1501, 0.2277, 0.2569, 0.0428]],

        [[0.5924, 0.1081, 0.2768, 0.0210],
         [0.3911, 0.6022, 0.0612, 0.6069],
         [0.4797, 0.8137, 0.1474, 0.8319]]])
tensor([[[0.9059, 0.3362, 0.4069, 0.6205],
         [0.8584, 0.9003, 0.9585, 0.0581],
         [0.1501, 0.2277, 0.2569, 0.0428]],

        [[0.5924, 0.1081, 0.2768, 0.0210],
         [0.3911, 0.6022, 0.0612, 0.6069],
         [0.4797, 0.8137, 0.1474, 0.8319]]])
tensor([[[1.1474, 1.1974, 0.5056, 1.5297],
         [1.2836, 1.6238, 1.2727, 1.0355],
         [0.6783, 0.7793, 0.4457, 0.4739]],

        [[0.8815, 0.1135, 0.4407, 0.3064],
         [0.5930, 1.0446, 0.6721, 0.9688],
         [0.8807, 1.4219, 0.2596, 1.3455]]])


In [25]:
a =t.ones(2, 3)
b = 3.0 * t.ones(2, 3)
c = a - b
print(c)

tensor([[-2., -2., -2.],
        [-2., -2., -2.]])


In [27]:
d = t.ones(2,2)
e = a - d

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [29]:
a = t.Tensor([[1,2], [3,4], [5, 6]])
print(a)

#数乘矩阵
b = 2.0 * a
print(b)

#对应点相乘，sum后即为卷积
c = a * b
print(c)
print(c.sum())

# a: 3 * 2, b.t():2 * 3
# d: 3 * 3
d = a.mm(b.t())
print(d)


# a.t(): 2 * 3, b.t():3 * 2
# e: 2 * 2
e = a.t().mm(b)
print(e)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])
tensor([[ 2.,  8.],
        [18., 32.],
        [50., 72.]])
tensor(182.)
tensor([[ 10.,  22.,  34.],
        [ 22.,  50.,  78.],
        [ 34.,  78., 122.]])
tensor([[ 70.,  88.],
        [ 88., 112.]])


In [31]:
a = t.Tensor([[1,2], [3,4], [5, 6]]) # 3 * 2
b = t.Tensor([[1,2],[3,4],[5,6],[7,8]]) # 4 * 2

c = a.mm(b.t()) # 3 * 4 
print(c)


#如果矩阵大小不满足 x: i * n, y:n * j的方式，则出错
c = a.mm(b)

tensor([[ 5., 11., 17., 23.],
        [11., 25., 39., 53.],
        [17., 39., 61., 83.]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x2)

In [33]:
#A: 3 * 2
#x: 1 * 2
A = t.Tensor([[1,2], [3,4], [5, 6]]) 
x = t.Tensor([[1, 2]])
print(A)
print(x)

# A: 3*2; b.t(): 2 * 1
# 结果：3 * 1
c = A.mm(x.t())
print(c)

#x: 1 * 2, A.t(): 2 * 3
# 结果: 1 * 3
d = x.mm(A.t())
print(d)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.]])
tensor([[ 5.],
        [11.],
        [17.]])
tensor([[ 5., 11., 17.]])


In [35]:
import torch as t
a=t.Tensor([[[1,2,3],[4,5,6]]])
print(a.size())
b=t.Tensor([1,2,3,4,5,6])
print(b.size())
print('====================')
print(a.view(1,6))
print(b.view(1,6))

torch.Size([1, 2, 3])
torch.Size([6])
tensor([[1., 2., 3., 4., 5., 6.]])
tensor([[1., 2., 3., 4., 5., 6.]])


In [37]:
a=t.Tensor([[[1, 2, 3, 4],[5,6,7,8]]])
print(a)
print('---------------------------------')
print(a.view(4,2))
print('---------------------------------')
print(a.view(2, 2 ,2))
print('---------------------------------')
c = a.view(4,2)
print('---------------------------------')
c[0,0] = 0
print(a)

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
---------------------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
---------------------------------
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
---------------------------------
---------------------------------
tensor([[[0., 2., 3., 4.],
         [5., 6., 7., 8.]]])


In [39]:
# Tensor的选取操作与numpy类似
x = t.rand(2,3,4)
print(x)
x[0, 0, :]

tensor([[[0.0408, 0.7066, 0.5215, 0.6337],
         [0.5243, 0.7225, 0.0467, 0.1921],
         [0.1591, 0.0143, 0.3100, 0.8154]],

        [[0.2725, 0.8133, 0.0938, 0.2713],
         [0.4265, 0.9915, 0.0691, 0.8761],
         [0.6872, 0.7358, 0.7744, 0.2410]]])


tensor([0.0408, 0.7066, 0.5215, 0.6337])

In [41]:
x[:, 0, 0] 

tensor([0.0408, 0.2725])

In [43]:
x[:, :, 0]

tensor([[0.0408, 0.5243, 0.1591],
        [0.2725, 0.4265, 0.6872]])

In [45]:
x[:,1:3, 2:4]

tensor([[[0.0467, 0.1921],
         [0.3100, 0.8154]],

        [[0.0691, 0.8761],
         [0.7744, 0.2410]]])

In [57]:
x1 = t.rand(2,2)
x2 = t.rand(2,2)
print(x1)
print(x2)

tensor([[0.6753, 0.7596],
        [0.3866, 0.2744]])
tensor([[0.3483, 0.0602],
        [0.3105, 0.3019]])


In [49]:
y = t.cat((x1, x2), dim=0)
print(y)

tensor([[0.5613, 0.0921],
        [0.9810, 0.7750],
        [0.9034, 0.7899],
        [0.1109, 0.3988]])


In [61]:
y = t.cat((x1,x2), dim=1)
print(y)

tensor([[0.6753, 0.7596, 0.3483, 0.0602],
        [0.3866, 0.2744, 0.3105, 0.3019]])


In [63]:
y = x1.unsqueeze(0)
print(y)
print(y.size())

tensor([[[0.6753, 0.7596],
         [0.3866, 0.2744]]])
torch.Size([1, 2, 2])


In [65]:
y = x1.squeeze(0)
print(y)
print(y.size())

tensor([[0.6753, 0.7596],
        [0.3866, 0.2744]])
torch.Size([2, 2])


In [67]:
y = t.chunk(x1, 2)
print(y)

(tensor([[0.6753, 0.7596]]), tensor([[0.3866, 0.2744]]))


In [75]:
y = t.chunk(x1, 2, dim=1)
print(y)

(tensor([[0.6753],
        [0.3866]]), tensor([[0.7596],
        [0.2744]]))


In [77]:
y = t.rand(2,3)
print(y)

tensor([[0.9879, 0.2375, 0.3435],
        [0.7134, 0.9943, 0.0370]])


In [83]:
y1 = t.reshape(y, (3, 2))
print(y1)

y1[0,0] = 0

print(y)

tensor([[0.0000, 0.2375],
        [0.3435, 0.7134],
        [0.9943, 0.0370]])
tensor([[0.0000, 0.2375, 0.3435],
        [0.7134, 0.9943, 0.0370]])


In [85]:
y1 = y.reshape(1, -1)
print(y1)

tensor([[0.0000, 0.2375, 0.3435, 0.7134, 0.9943, 0.0370]])


In [87]:
#PyTorch Tensor与Numpy之间的转换
#tensor->numpy
a = t.ones(2, 3, 4)
b = a.numpy()
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [89]:
# numpy --> Tensor
import numpy as np
a = np.ones(5)
b = t.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [91]:
# 上述转换中，Tensor和Numpy共享内容，所以修改一个另一个也随之改变

print(a)
b.add_(1) #注意是下划线add_
print(a)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


In [101]:
#支持GPU，将x和y都转移到GPU中进行运算
# 在大规模数据复杂Tensor运算时，具有优势；
# 小规模数据时由于具有数据转移开销，CPU会更快一点

#本机器不支持GPU，不会运行以下代码
x = t.rand(2,3)
y = t.rand(2,3)

if t.cuda.is_available():
    x = x.cuda() #将张量x转移到GPU中
    y = y.cuda() #将张量y转移到GPU中
    z = x + y #在GPU中运算x + y
else:
    print("No GPUs")
    z = x + y
print(z)

No GPUs
tensor([[1.0448, 0.9193, 1.5216],
        [1.5478, 1.1833, 0.4076]])


In [103]:
#如果不进行判断，x.cuda()语句在没有GPU环境的情况下出错
x = x.cuda() #将张量x转移到GPU中
y = y.cuda() #将张量y转移到GPU中
x + y #在GPU中运算x + y

AssertionError: Torch not compiled with CUDA enabled

In [105]:
# 求函数 y= x^2 在x=3时的导数: y'(3) = dy/dx|x=3

x=t.tensor(3.0,requires_grad=True)
y=x.mul(x)

#判断x,y是否是可以求导的
print(x.requires_grad)
print(y.requires_grad)

#求导，通过backward函数来实现
y.backward()

#查看导数，也即所谓的梯度
print(x.grad)

True
True
tensor(6.)


In [107]:
# 练习
# 求y = max(0, x)在x=1和x=-1处的导数


#定义x=1.0 和y=max(0, x)
x = t.tensor(1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))

#调用backward并打印导数
y.backward()
print(x.grad)

# 改变x后需要重新执行y和backward
x = t.tensor(-1.0, requires_grad=True)
y = t.max(x, t.zeros(1,1))
y.backward()
print(x.grad)

tensor(1.)
tensor(0.)


In [109]:
# 求y = 1/x
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal(x)
y.backward()
print(x.grad)



tensor(-4.)
tensor(-1.)
tensor(-0.2500)


In [111]:
# 求y = 1/\sqrt(x)
x = t.tensor(0.5, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(1.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

x = t.tensor(2.0, requires_grad=True)
y = t.reciprocal( t.sqrt(x))
y.backward()
print(x.grad)

tensor(-1.4142)
tensor(-0.5000)
tensor(-0.1768)


In [113]:
# 求y = 1/\sqrt(x)
x = t.tensor(1.0, requires_grad=True)
g = t.sqrt(x)
y = t.reciprocal(g)

g.backward(retain_graph=True)
print(x.grad)


y.backward(retain_graph=True)
print(x.grad)


tensor(0.5000)
tensor(0.)


In [109]:
# f(x,y) = x^2 + 2 * y^2 + xy
# 在 (1.0, 1.0)处的导数
x = t.tensor(1.0, requires_grad=True)
y = t.tensor(1.0, requires_grad=True)

f = x.pow(2) + t.tensor(2.0).mul(y.pow(2)) + x.mul(y)
f.backward()
print(x.grad)
print(y.grad)

tensor(3.)
tensor(5.)


In [111]:
# f(x,y, z) = ln(e^x + e^y + e^z)
# 在 (0.0, 2.0, 5.0)处的导数
x = t.tensor(0.0, requires_grad=True)
y = t.tensor(2.0, requires_grad=True)
z = t.tensor(5.0, requires_grad=True)

f = t.log(t.exp(x) + t.exp(y) + t.exp(z))
f.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor(0.0064)
tensor(0.0471)
tensor(0.9465)


In [113]:
# 注意：把x和b定义为一个2*1的矩阵，x.mm()是矩阵乘法
import torch as t
x = t.tensor([[1.0], [2.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, A, b)
print()

f = x.t().mm(A).mm(x) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[14.]], grad_fn=<AddBackward0>)

tensor([[ 7.],
        [10.]])


In [115]:

x = t.tensor([[1.0], [2.0]], requires_grad=True)
y = t.tensor([[3.0], [4.0]], requires_grad=True)

A = t.tensor([[1.0, 1.0], 
              [1.0, 2.0]])
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
print(x.grad)
print(y.grad)

tensor([[1.],
        [2.]], requires_grad=True) tensor([[3.],
        [4.]], requires_grad=True) tensor([[1., 1.],
        [1., 2.]]) tensor([[1.],
        [0.]])

tensor([[30.]], grad_fn=<AddBackward0>)

tensor([[ 8.],
        [11.]])
tensor([[3.],
        [5.]])


In [117]:
# f(A) = x^T A y + x^T b
x = t.tensor([[1.0], [2.0]])
y = t.tensor([[3.0], [4.0]])

A = t.tensor([[2.0, 12.0], 
              [1.0, 2.0]], requires_grad=True)
b = t.tensor([[1.0], [0.0]])
print(x, y, A, b)
print()

f = x.t().mm(A).mm(y) + x.t().mm(b)
print(f)
print()
f.backward()
#print(x.grad)
#print(y.grad)
print(A.grad)

tensor([[1.],
        [2.]]) tensor([[3.],
        [4.]]) tensor([[ 2., 12.],
        [ 1.,  2.]], requires_grad=True) tensor([[1.],
        [0.]])

tensor([[77.]], grad_fn=<AddBackward0>)

tensor([[3., 4.],
        [6., 8.]])
